- app/actions/ModActionPanel/QuickAction.tsx
- components/common/Card.tsx
- components/common/RecordCard.tsx
- components/reports/helpers/subject.ts
- components/subject/ReviewStateMarker.tsx
https://github.com/bluesky-social/ozone/assets/1919066/a04134e8-562f-4a4e-a2c3-86d29bf2b595
> :lipstick: Handle reviewNone, labeler account display and sticky note more prominent

- app/configure/page-content.tsx
- package.json
- yarn.lock
Adding a couple missing options here on the service record.  Updated the API package w/ supporting types.
> More comprehensive service record settings, update api package

- app/configure/page-content.tsx
- components/shell/ConfigurationFlow.tsx
Ensures Bluesky labelers are aware of the app's labeler community guidelines during setup/configuration flows.
> Add community guidelines to service record setup

- components/email/template-selector.tsx
> :lipstick: Add placeholder in template selector

- components/common/feeds/AuthorFeed.tsx
- components/common/posts/Posts.tsx
- components/common/posts/PostsFeed.tsx
- components/repositories/AccountView.tsx
Depends on https://github.com/bluesky-social/atproto/pull/2374
> :sparkles: Let mods search posts on author feed

- components/common/posts/PostsFeed.tsx
Addresses https://github.com/bluesky-social/ozone/issues/73
> :lipstick: Show alt text under images

- app/configure/page-content.tsx
With the JSON editor, users can't easily paste in large change when editing labeler service record. This PR adds an alternative plain text editor to facilitate that.
https://github.com/bluesky-social/ozone/assets/1919066/7bb6b7a2-c5d6-4fb4-bdb7-39c1ce113112
> :lipstick: Allow editing labeler service record in plain text

- CHANGELOG.md
- service/package.json
- service/yarn.lock
- Update package version for `@atproto/ozone` package to latest
- Update yarn lock file to reflect the new version
- Add a changelog file
> :bookmark: Changelog and preparation for new tag

- app/actions/ModActionPanel/QuickAction.tsx
- components/repositories/AccountView.tsx
- lib/client.ts
- package.json
- yarn.lock
> On post from deactivated account
> On account page
> :sparkles: Show account deactivation flag in action panel and account page

- components/common/posts/PostsFeed.tsx
- components/dms/MessageContext.tsx
- package.json
- yarn.lock
> :sparkles: Show embedded record in message context view

- components/mod-event/EventList.tsx
> :sparkles: Show subject context when viewing events by an author

- app/events/filters/macros/page.tsx
- components/mod-event/CreateMacroForm.tsx
- components/mod-event/EventList.tsx
- components/mod-event/FilterPanel.tsx
- components/mod-event/MacroPicker.tsx
- components/mod-event/constants.ts
- components/mod-event/helpers/macros.ts
- components/mod-event/useFilterMacrosList.tsx
- components/mod-event/useModEventList.tsx
- components/shell/CommandPalette/actions.ts
This PR adds a new feature that allows users to save event filter in their browser. Saved filters can be easily applied with one click to easily acquire a smaller subset of events in any place the entire event log is being displayed.
https://github.com/bluesky-social/ozone/assets/1919066/0df2da13-6430-41d9-893b-fc1d9758070b
> ✨ Filter macros

- app/repositories/[id]/[...record]/page-content.tsx
This PR passes admin token when calling `getList` so that takendown records are returned. It also adds graceful fallback for any record loading failure so that we at least show the skeleton UI that lets moderators action the record being viewed.
> :sparkles: Graceful fallback if record loading fails

- components/workspace/Panel.tsx
- components/workspace/PanelActionForm.tsx
> :sparkles: Allow removing tags and labels from workspace

- components/repositories/AccountView.tsx
- components/signature/RelatedAccounts.tsx
- package.json
- yarn.lock
Building on https://github.com/bluesky-social/atproto/pull/2855
Provide a page on the account view for correlating bad actors such as ban evaders and bot waves across various threat signatures supplied from the entryway. Note that these threat signatures should be obfuscated and privacy-preserving (and are in Bluesky's implementation)
> Related accounts

- components/repositories/AccountView.tsx
- components/signature/RelatedAccounts.tsx
- package.json
- yarn.lock
Screwed up the merge of https://github.com/bluesky-social/ozone/pull/213 so re-opening
> Related accounts 2

- app/repositories/[id]/[...record]/page-content.tsx
- components/list/Accounts.tsx
- components/repositories/RecordView.tsx
This PR refactors list members view into its own component and adds an option to add all members of a list to workspace.
> :sparkles: Allow adding all members of a list to workspace

- service/package.json
- service/yarn.lock
The new version fixes the issue with ozone landing page showing ascii art instead of the login page.
> :arrow_up: Update @atproto/ozone version

- app/actions/ModActionPanel/QuickAction.tsx
- components/common/PreviewCard.tsx
- components/common/RecordCard.tsx
- components/common/feeds/AuthorFeed.tsx
- components/common/posts/Posts.tsx
- components/common/posts/PostsFeed.tsx
- components/common/video/helpers.ts
- components/repositories/AccountView.tsx
- lib/constants.ts
This PR adds a env var driven fallback URL to help view videos from takendown or deactivated accounts.
> ✨ Add video fallback url

- app/actions/ModActionPanel/QuickAction.tsx
- components/mod-event/EventItem.tsx
- package.json
- service/package.json
- service/yarn.lock
- yarn.lock
This PR allows adding a expiration time when labeling.
> Duration selector
> Expiring label event card
> Label detail view
> :sparkles: Allow creating labels with expiry

- components/config/Member.tsx
- components/team/RolePicker.tsx
- components/team/StatusPicker.tsx
- components/team/useMemberList.tsx
- tsconfig.json
Depends on https://github.com/bluesky-social/atproto/pull/3554
> :sparkles: Add role and status filter for team list

- components/reports/QueueFilter/Tag.tsx
Naive attempt to address: https://github.com/bluesky-social/ozone/issues/288
> add 'report:sexual' to set of queue filters

- components/common/CopyButton.tsx
- components/repositories/AccountView.tsx
- components/repositories/useCopyAccountDetails.tsx
https://github.com/user-attachments/assets/5d0c82bf-b06d-40fe-831c-68acf656bd69
> :sparkles: Copy full profile details to clipboard action

- components/reports/helpers/getType.ts
Closes: https://github.com/bluesky-social/ozone/issues/307
> fix hassment typo

- components/workspace/FilterSelector.tsx
Allow filtering workspace entries by minimum account age
> :sparkles: Add account age filter to workspace

- components/config/Member.tsx
- components/config/Sets.tsx
Didn't realize searching perf is so bad in prod. This PR debounces URL update to ensure search input feels smooth.
> :zap: Debounce search input to improve typing perf

- app/actions/ModActionPanel/QuickAction.tsx
- components/common/ActionPanel.tsx
- components/common/Dropdown.tsx
- components/common/FullScreenActionPanel.tsx
- components/common/RichText.tsx
- components/common/feeds/AuthorFeed.tsx
- components/common/labels/List.tsx
- components/common/modals/confirmation.tsx
- components/communication-template/delete-confirmation-modal.tsx
- components/email/template-selector.tsx
- components/mod-event/DetailsPopover.tsx
- components/mod-event/SelectorButton.tsx
- components/reports/ModerationForm/ActionDurationSelector.tsx
- components/reports/ModerationForm/ActionPolicySelector.tsx
- components/reports/QueueFilter/Panel.tsx
- components/repositories/Finder.tsx
- components/repositories/InviteCodeGenerationStatus.tsx
- components/shell/MobileMenu.tsx
- components/shell/ProfileMenu.tsx
- components/subject/table.tsx
- components/team/RolePicker.tsx
- components/workspace/ExportPanel.tsx
- components/workspace/FilterSelector.tsx
- components/workspace/Panel.tsx
- components/workspace/utils.ts
- package.json
- yarn.lock
Primary change here was to upgrade to @latest version of headlessui/react package and then remove the `Transition` wrapper component for menu items where menu items change dynamically based on memoized value.
Took the time to migrate all namespaced components to root level components as well.
> :bug: Fix react v19 related bug in headlessui 

- components/mod-event/helpers/emitEvent.tsx
This PR adds a 10s delay to email action allowing moderators a small window to undo the action.
https://github.com/user-attachments/assets/0a16962c-4ed5-4f65-8ac5-912dcd43a590
> :sparkles: Add undo option to email action

- components/repositories/AccountHistory.tsx
- components/repositories/AccountView.tsx
- package.json
- yarn.lock
> :sparkles: Add account history table in profile view page

- app/verification/page-content.tsx
- components/verification/FilterPanel.tsx
- components/verification/useTrustedVerifiers.tsx
- components/verification/useVerificationList.tsx
> :sparkles: Add quick filter to only show verifications from trusted verifiers

- app/verification/page-content.tsx
- components/verification/ActionButton.tsx
- components/verification/FilterPanel.tsx
- components/verification/useVerificationList.tsx
- Default to trusted verifier issuer filter on initial load of verification list
- Avoid issuing verification record for profiles without display name
- Add a copy DID button next to all trusted verifiers
> ❇️ Verification list filter improvements
