bluesky-social/ozone

- app/actions/ModActionPanel/BlobList.tsx
- app/actions/ModActionPanel/QuickAction.tsx
- app/repositories/[id]/[...record]/page.tsx
- components/common/PreviewCard.tsx
- components/mod-event/helpers/subject.tsx
- components/reports/helpers/subject.ts
- components/repositories/RedirectFromhandleToDid.tsx
- components/shell/CommandPalette/useAsyncSearch.tsx
- components/subject/table.tsx
- lib/util.ts
This PR fixes 
1. order of items in cmd palette. Prioritize action panel opener for record when available, account (through did or handle) otherwise.
2. matcher for did, handle, bsky url and at-uri
3. handle -> did replaces when navigating to record url 
4. spacing in the moderation queue table so that notes column does not take up too much space
5. On mobile safari, the botton address bar hiding content at the bottom of the quick action panel
> Cmd palette fixes

- components/subject/ReviewStateMarker.tsx
**Issue:**
Currently, REVIEWNONE icons are not visible on the dark theme. 
**Change:**
I added a `reviewStateToColor` for `ToolsOzoneModerationDefs.REVIEWNONE` so help make it visible on the dark theme.
<br />
> Change colors to for ReviewStateMarker so ReviewNone is visible on dark theme

- HOSTING.md
closes: https://github.com/bluesky-social/ozone/issues/57
Also added `openssl`, though I think that is usually already installed, or a dep of one of the other tools.
> add xxd dep to HOSTING doc

- components/common/Alert.tsx
- components/shell/LoginModal.tsx
- lib/client.ts
This PR allows accounts with 2FA to log into ozone.
> When 2FA input is needed
> When wrong 2FA code is entered
> :sparkles: Allow logging in with 2fa code

- app/actions/ModActionPanel/QuickAction.tsx
- components/common/posts/ReplyParent.tsx
- components/mod-event/SelectorButton.tsx
Addresses https://github.com/bluesky-social/ozone/issues/101
This PR improves linking around reply posts. In ozone, when a reply post is shown, mods may want to review the parent post or the author account of the parent post. With this PR, both are available inline and the special case where the author of the parent post blocked the reply author is also handled.
Sneaking in an unrelated fix with this to hide reporter muting actions on non-repo subjects.
> :lipstick: Show links to post and author action panel for replies

- CHANGELOG.md
- components/mod-event/SelectorButton.tsx
Mute/Unmute reporter event should only displayed when the subject is a DID. The previous implementation for that check was filtering out all event types when subject is not DID.
> :bug: Fix filter for mute reporter event display in selector button

- components/common/RecordCard.tsx
- components/common/posts/PostsFeed.tsx
Since `getPostThread` does not return post record data when there's a block relationship between author and the moderator viewer, this PR builds the post data from `getRecord` so that post preview is displayed properly in the quick action panel.
> :sparkles: Show post preview even when moderator is blocked by the author

- app/repositories/page-content.tsx
`term` param has been deprecated in favor of `q` https://github.com/bluesky-social/atproto/pull/2507
> :sparkles: Use q instead of term for searcning repos

- components/list/Lists.tsx
- components/repositories/AccountView.tsx
Depends on https://github.com/bluesky-social/atproto/pull/2493
This PR shows a new `Lists` tab on user's profile screen which shows all lists the user is associated with.
> Dark Mode
> Light Mode
> :sparkles: Show list tab on user profile page

- components/common/PreviewCard.tsx
- components/common/RecordCard.tsx
- components/common/srtarterpacks/RecordCard.tsx
- components/common/starterpacks/RecordCard.tsx
- components/reports/SubjectOverview.tsx
- components/reports/helpers/subject.ts
- components/repositories/RecordView.tsx
- lib/constants.ts
- package.json
- yarn.lock
https://github.com/bluesky-social/ozone/assets/1919066/5186f5bd-fc55-4555-804d-2efaf9fe2be3
> :sparkles: Add starterpack support

- app/layout.tsx
- components/common/RecordCard.tsx
- components/common/feeds/RecordCard.tsx
- components/common/posts/ImageList.tsx
- components/common/posts/PostsFeed.tsx
- components/common/posts/PostsTable.tsx
- components/list/RecordCard.tsx
- lib/util.ts
- package.json
- yarn.lock
This PR introduces a lightbox plugin to open images within a modal instead of opening them in a new tab. This allows moderators to view and navigate images in full size.
The plugin being used is https://yet-another-react-lightbox.com/
While testing, I also found a few UI issues with text color being off in some places so those were fixed too.
> Screenshot from a post's image being opened in lightbox showing thumbnails and alt text as caption
> :sparkles: Add modal image viewer

- components/common/feeds/AuthorFeed.tsx
- components/common/posts/Filter.tsx
- components/common/posts/Posts.tsx
- components/common/posts/constants.ts
This PR adds new filters for moderators to view specific types of posts from a user, such as excluding replies, showing media only, reposts only, and quotes only posts. Some of the filtering happens client-side and mutually exclusive with the existing keyword search due to differing data sources.
https://github.com/bluesky-social/ozone/assets/1919066/1242e2a3-4951-4c6f-9dd7-b7d83cf3a7be
> :sparkles: Add Repost, quote, media and no reply filters to author feed

- app/actions/ModActionPanel/QuickAction.tsx
- app/communication-template/page.tsx
- components/config/Member.tsx
- components/mod-event/SelectorButton.tsx
- components/repositories/AccountView.tsx
- cypress/e2e/cmd-palette/main.cy.ts
- cypress/fixtures/auth.json
- cypress/support/api.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- lib/server-config.ts
Since next.js generates static pages on build, attempting to access `client.session` in any of the paths that may get rendered in the static build triggers an auth error. So, this PR refactors the permission checks into a helper function that handles said error.
> :bug: Fix permission fetching

- components/common/posts/PostsFeed.tsx
> :sparkles: Show embedded list in post card

- components/common/posts/PostsFeed.tsx
- components/repositories/useSearchActorsTypeahead.tsx
- components/shell/CommandPalette/useAsyncSearch.tsx
Backend PR needs to be merged first https://github.com/bluesky-social/atproto/pull/2612
This PR triggers a user typeahead search from command palette when the search query starts with @ allowing moderators to look at a list of users and pick one to action on.
https://github.com/bluesky-social/ozone/assets/1919066/704e5c7b-6bda-4346-9900-39a34b32fd79
> :sparkles: Add typeahead search in cmd palette

- components/common/feeds/Likes.tsx
- components/common/feeds/Reposts.tsx
- components/repositories/RecordView.tsx
[Backend PR](https://github.com/bluesky-social/atproto/pull/2624) needs to be merged first.
This allows mods to view Likes and Reposts of a post from within ozone. This is especially helpful for takendown posts/users liking/reposting posts.
> :sparkles: Add Likes and Repost viewer in post thread view

- app/actions/ModActionPanel/QuickAction.tsx
- components/common/labels/List.tsx
- components/mod-event/SelectorButton.tsx
- components/shell/ConfigurationFlow.tsx
- components/team/MemberEditor.tsx
- lib/client.ts
- service/package.json
- service/yarn.lock
This PR ensures that initial labeler set up steps can continue on without getting blocked by attempts to fetch server config.
> 🐛 Fix new labeler config steps

- components/mod-event/EventItem.tsx
- components/mod-event/EventList.tsx
- components/mod-event/FilterPanel.tsx
- components/mod-event/useModEventList.tsx
This PR adds the ability to show preview content for each event when viewing the event stream. This is especially helpful when reviewing events on different subjects/accounts.
https://github.com/user-attachments/assets/8b0d0f00-74ae-43c0-bc10-5f2bd082a0e4
> :sparkles: Toggleable preview cards in event viewer

- app/actions/ModActionPanel/QuickAction.tsx
- cypress/fixtures/seed.json
When taking label action, the label selector shows all labels that are currently applied on the subject and as a result, any label applied by an external labeler can be `unselected`. However, in reality, this doesn't do anything since one can not remove a label applied by an external labeler. 
To reduce confusion around this, this PR removes external labelers from label selector.
> :bug: Don't show external label in label selector

- app/reports/page-content.tsx
Depends on https://github.com/bluesky-social/atproto/pull/2777
https://github.com/user-attachments/assets/e36fc543-99db-4378-854b-a62d3db043bf
> :bug: Allow Only/Exclude/Indifferent filters for appeal status

- app/repositories/page-content.tsx
- components/common/feeds/PostThread.tsx
- components/graph/Followers.tsx
- components/graph/Follows.tsx
- components/mod-event/helpers/emitEvent.tsx
- components/repositories/AccountView.tsx
- components/repositories/Blocks.tsx
- components/repositories/RecordView.tsx
- components/subject/useSubjectStatus.tsx
- components/workspace/Panel.tsx
- components/workspace/hooks.tsx
- lib/util.ts
This PR adds a bunch of new improvements to workspace feature
1. Take action in batches. If there are too many actions to be taken, we will now batch 50 actions at a time and then add a cooling period after each batch before firing the next one.
2. Add all search results from repositories page to workspace. This allows mods to search for a user with a keyword and all matching users to workspace.
3. Add all followers of a user to workspace.
4 Add all follows of a user to workspace.
> Workspace improvements

- app/reports/page-content.tsx
Addressing this scenario https://github.com/bluesky-social/ozone/pull/170#discussion_r1742276536
> :bug: Only use recognized values for appealed query param

- app/reports/page-content.tsx
- components/common/Dropdown.tsx
- components/common/EmbedTypePicker.tsx
This allows moderators to look at reported content based on their embedded content types.
**Note**: It does not work with language filter since it uses tags for filtering and a backend limitation of how tag filter works as an OR condition instead of AND when there are multiple tags.
> Light mode
> Dark mode
> :sparkles: Add embed type filter for moderation queue

- components/common/posts/PostsFeed.tsx
- components/common/video/player.tsx
> Subtitle option
> Lang specific subtitles
> :sparkles: Show subtitles in videos, if there are any

- app/actions/ModActionPanel/QuickAction.tsx
Currently, if a user applies a self label `porn` and automod also labels the post with `porn`, the label selector won't show `porn` as already selected because it thinks `porn` is a self label, hence, not removable. This PR fixes it.
> :bug: Show all labels in selector that can be edited by labeler

- app/reports/page-content.tsx
- components/common/labels/util.ts
- components/common/posts/PostsFeed.tsx
- components/common/posts/PostsTable.tsx
- components/common/video/player.tsx
- components/config/Labeler.tsx
- components/config/LocalPreferences.tsx
- components/config/useLocalPreferences.tsx
- components/repositories/AccountView.tsx
- components/repositories/ProfileAvatar.tsx
This PR adds a localstorage based preference that allows users to choose 3 possible filters on media content with certain labels. Previously, we were only applying a blur filter for all these labels and now, along with blur, media can be black and white and translucent, according to user's preference. 
**By Default we will apply all 3 filters for those labels**
> Dark mode
> Light mode
Additionally, this PR adds modal image viewer for profile avatar and profile banner image.
> :lipstick: Make graphic media less visible

- app/reports/page-content.tsx
- lib/constants.ts
- lib/util.ts
This should allow us to rebalance queues if they get lopsided by adjusting the seed via `NEXT_PUBLIC_QUEUE_SEED`.  This will reshuffle content that appears in each queue.
> Update queue sharding so that it can be rebalanced using a seed

- app/actions/ModActionPanel/QuickAction.tsx
- components/common/RecordCard.tsx
- components/common/feeds/Likes.tsx
- components/common/feeds/PostThread.tsx
- components/common/posts/PostsFeed.tsx
- components/repositories/RecordView.tsx
This PR adds a `Add to workspace` button in the likes tab of a post which functions similarly to the follows and followers tab and allows mods to add all users who liked a post to workspace.
Additional tweaks
1. Show likes and repost counts on post thread
3. Show followers, follows and posts count on profile card
2. Keep current view state in the URL on record view page
> :sparkles: Allow users to bulk add all users who liked a post to workspace

- components/mod-event/EventList.tsx
- components/mod-event/useModEventList.tsx
This PR adds a `Add to workspace` workflow in the event stream. This helps moderator do bulk action/investigation using data from the event stream.
https://github.com/user-attachments/assets/55dc7dd9-04c3-4b40-95f1-dee2976a2a9f
> :sparkles: Allow taking subjects from event stream to workspace

- components/subject/table.tsx
> :sparkles: Show more descriptive message when queue empty content is shown

- components/reports/SubjectOverview.tsx
Missed this in the first iteration #199
> :bug: Only open action panel for subject author in subject overview

- components/team/Role.tsx
New members are normally added as "triage". The current ordering of the role dropdown uses "admin" is a default. This just inverts the order so that the default is to onboard someone with the least permissions
> Invert role order when adding new member

- app/search/page-content.tsx
- app/search/page.tsx
- components/common/feeds/AuthorFeed.tsx
- components/search-content/useContentSearch.tsx
- components/shell/common.ts
This PR adds a dedicated page to show top and latest posts for a search keyword which surfaces the same content as the app. This helps moderators to quickly find and proactively action content without having to go through the app.
> :sparkles: Add search page

- app/search/page-content.tsx
- app/search/page.tsx
Using the props on root level page causes the searchParams to not work when exported as static page. This PR moves the search query fetching to client side hook.
> :bug: use search param hook to ensure that client side search is triggered

- components/repositories/AccountView.tsx
Hcap details were changed from a record format (`{[property]: value}`) to an array format (`{property, value}[]`).
> Fix hcap detail

- app/search/page-content.tsx
- components/mod-event/SelectorButton.tsx
- components/workspace/PanelActionForm.tsx
This PR adds the resolve appeal action in workspace and fixes infinite loader display issue on search page.
> :sparkles: Show resolve appeal action on workspace

- app/actions/ModActionPanel/QuickAction.tsx
- components/common/labels/Selector.tsx
- components/mod-event/FilterPanel.tsx
- components/mod-event/useModEventList.tsx
- components/repositories/Blocks.tsx
- components/repositories/api.ts
- components/workspace/PanelActionForm.tsx
This PR fixed event filters so that tag based events and appeal event filter work correctly. These are pseudo event types so there's no 1-to-1 mapping for these and the actual filter need to be built manually.
> :bug: Build correct event filter for appeal and tags

- components/shell/ConfigContext.tsx
- components/shell/ConfigurationContext.tsx
- components/shell/ConfigurationContext/useServerConfigQuery.ts
- lib/useStoredQuery.ts
The server config is stored in the local storage to allow cached access when loading the app. However, the cache key is the same for every user.
This PR adds a `useCachedQuery` that combines the `useQuery` and `useLocalStorage` hooks using a consistent cache key mechanism for both the cache and query key.
> Prevent use of another user's server-config

- app/search/page-content.tsx
- components/repositories/AccountView.tsx
- components/search-content/useContentSearch.tsx
This PR adds a new `People` tab on the search page similar to the app's search page which shows all users matching the search query.
> :sparkles: Add people tab on search page

- components/mod-event/EventItem.tsx
- components/mod-event/ItemTitle.tsx
- components/mod-event/useModEventList.tsx
- components/subject/ReviewStateMarker.tsx
This PR hydrates repo and record details on the client side for each event and shows the moderation status of the subject of when viewing event stream.
> :sparkles: Load and display moderation status in event list

- components/common/Dropdown.tsx
- components/common/FullScreenActionPanel.tsx
- components/common/labels/List.tsx
- components/mod-event/SelectorButton.tsx
- components/shell/CommandPalette/Root.tsx
- components/workspace/FilterSelector.tsx
- components/workspace/PanelActionForm.tsx
Besides the reverse takedown action in workspace, this PR also adjusts z-index values across various panels and popovers to fix content overlap issues reported by mods.
> :sparkles: Allow reverseTakedown from workspace

- components/mod-event/EventList.tsx
- components/mod-event/FilterPanel.tsx
- components/mod-event/useModEventList.tsx
When investigating and actioning large blocks of accounts/posts, mods often need to look at event stream in depth and being limited to 25 items per page is quite annoying. However, for quick action panel and other places, 25 items are more than enough for most cases. So making the page size configurable gets us the best of both worlds.
https://github.com/user-attachments/assets/6808e3c4-fe71-43f0-b3c7-2934a73a3e39
> :sparkles: Allow managing page size for event stream

- app/reports/page-content.tsx
- components/config/Labeler.tsx
- components/config/LocalPreferences.tsx
- components/config/external-labeler.tsx
- components/mod-event/EventItem.tsx
- package.json
- service/package.json
- service/yarn.lock
- yarn.lock
Depends on https://github.com/bluesky-social/atproto/pull/3280
This PR removes the client side queue splitting and passes the queue config to the request when calling `queryStatuses` so that the db query on the server can take care of the splitting.
> :sparkles: Pass queue config to the server query when fetching statuses

- app/actions/ModActionPanel/QuickAction.tsx
- app/configure/page-content.tsx
- components/config/Policies.tsx
- components/mod-event/EventItem.tsx
- components/mod-event/EventList.tsx
- components/mod-event/FilterPanel.tsx
- components/mod-event/useModEventList.tsx
- components/reports/ModerationForm/ActionError.tsx
- components/reports/ModerationForm/ActionPolicySelector.tsx
- components/setting/policy/Editor.tsx
- components/setting/policy/List.tsx
- components/setting/policy/types.ts
- components/setting/policy/usePolicyList.tsx
- components/setting/policy/utils.ts
- components/setting/useQueueSetting.ts
- components/shell/CommandPalette/Root.tsx
- components/shell/CommandPalette/actions.ts
- components/workspace/Panel.tsx
- components/workspace/PanelActionForm.tsx
- package.json
- service/package.json
- service/yarn.lock
- tsconfig.json
- yarn.lock
Depends on https://github.com/bluesky-social/atproto/pull/3271
This PR adds a new setting panel for managing a list of policies for takedown action. When taking a subject down moderators can *optionally* chose a policy from the list to associate with the takedown. 
https://github.com/user-attachments/assets/7ac61b69-c7a4-451a-99ed-907ec78e126b
> ✨ Takedown policy association

- app/actions/ModActionPanel/QuickAction.tsx
- app/reports/page-content.tsx
- components/common/buttons.tsx
- components/mod-event/EventList.tsx
- components/mod-event/useModEventList.tsx
- components/reports/QueueFilter/Panel.tsx
- components/reports/QueueFilter/Stats.tsx
- components/reports/useQueueFilter.tsx
- components/repositories/RepositoriesTable.tsx
- components/subject/Summary.tsx
- components/subject/table.tsx
- package.json
- service/package.json
- service/yarn.lock
- yarn.lock
Depends on https://github.com/bluesky-social/atproto/pull/3236
This PR shows moderation stats/summary for subjects/accounts.
> Stats preview in the queue table
> Sort config for stats
> Full stats view in quick action panel
> Stats summary in quick action panel
> Stats filter view
> :sparkles: Show subject stats/summary

- app/reports/page-content.tsx
- components/reports/useQueueFilter.tsx
- components/repositories/AccountView.tsx
- components/repositories/RepositoriesTable.tsx
- components/repositories/helpers.ts
- components/subject/table.tsx
- Threat sig details on the repositories page help mods quickly find correlation and skim through long list of accounts
- Bugfix to trigger statuses refresh when minRecordTakedown is changed
> :bug: Fix min record takedown filter and add stats on repositories page

- components/mod-event/EventList.tsx
- components/mod-event/FilterPanel.tsx
- components/mod-event/useModEventList.tsx
- components/reports/QueueFilter/SubjectType.tsx
This PR brings the already available filters for subject type and record collection to the event list allowing moderators to monitor events on account or record of certain collections either from event page or the quick action panel.
> :sparkles: Show subject type and collection filter in events filter panel

- components/common/feeds/Likes.tsx
- components/common/feeds/Reposts.tsx
- components/graph/Followers.tsx
- components/graph/Follows.tsx
- components/workspace/SubjectsToWorkspaceAction.tsx
This PR adds `Add to workspace button` to the reposts tab for posts. Additionally, it refactors the `Add to workspace` feature into a shareable component and replaces the manual implementation on Likes, Followers and Follows tabs with the shared component.
> ❇️ Add reposters to workspace

- app/reports/page-content.tsx
- components/reports/QueueSelector.tsx
- components/setting/useQueueSetting.ts
- components/subject/useSubjectStatus.tsx
This PR makes default queue config only applicable to non-escalation tabs and adds an additional flag per queue config to make a queue available on the escalation tab. This makes it really easy to have different number of queues for `triage` and `moderator` roles.
> :sparkles: Separate triage and escalation queue config

- components/subject/PriorityScore.tsx
- components/subject/Summary.tsx
Not great, but at least a bit better. My web accessibility dev tool thing isn't detecting/confirming if this is enough.
Top is changed colors, bottom is old colors.
This is related to @rahaeli's https://github.com/bluesky-social/ozone/issues/310
Maybe even better/clearer would be something like `border-2 border-blue-400`? I'm not sure if that is clear enough for any current workflows, and hesitant to make a bigger change w/o mod team feedback.
> improve info tag contrast

- components/config/Member.tsx
- components/config/ProtectedTags.tsx
- components/repositories/AccountView.tsx
- components/repositories/Blocks.tsx
- components/repositories/Finder.tsx
- components/repositories/api.ts
- components/repositories/useCopyAccountDetails.tsx
- components/setting/protected-tag/Editor.tsx
- components/setting/protected-tag/useProtectedTag.tsx
- components/team/MemberList.tsx
- components/team/helpers.ts
- components/team/useMemberList.tsx
- package.json
- service/package.json
- service/yarn.lock
- yarn.lock
Depends on https://github.com/bluesky-social/atproto/pull/3587
This PR adds search feature on team member page and uses the newly available search api in other places where full team member list was being loaded to allow searching by handle/name.
Adds some refactors in usage of getProfiles and fixes formatting issue in user info copy feature.
https://github.com/user-attachments/assets/5375b859-1e6c-4987-8fbe-ba04e35a55a2
> ❇️ Team member search

- app/actions/ModActionPanel/QuickAction.tsx
- app/reports/page-content.tsx
- components/common/Alert.tsx
- components/common/RecordCard.tsx
- components/common/TextWithLinks.tsx
- components/mod-event/EventItem.tsx
- components/mod-event/helpers/emitEvent.tsx
- components/repositories/HighProfileWarning.tsx
- components/repositories/helpers.ts
- components/subject/RecordAuthorStatus.tsx
- components/subject/ReviewStateMarker.tsx
- components/tags/SubjectTag.tsx
- components/workspace/FilterContext.tsx
- components/workspace/FilterSelector.tsx
- components/workspace/FilterView.tsx
- components/workspace/List.tsx
- components/workspace/Panel.tsx
- components/workspace/hooks.tsx
- components/workspace/types.ts
- components/workspace/useWorkspaceListData.tsx
- components/workspace/utils.ts
- package.json
- yarn.lock
Depends on https://github.com/bluesky-social/atproto/pull/3651
This PR refactors workspace data loading to use `tools.ozone.moderation.getSubjects` endpoint and adds a more advanced filtering system for workspace items that allows grouping and using OR filters between groups. 
Thanks to the unified dataloader, workspace can now also filter by follower count and other profile info and shows warnings when workspace has high profile accounts in it.
> High profile warning in workspace action form
> Advanced grouped filtering for workspace items
Few little touches here and there
1. show star icon in workspace item rows for items of high profile account
2. change label prefix `report:` to a flag icon to save real-estate and make workspace items more legible
3. change `lang:und` tag to `lang?` …
> ❇️ Use subject view for workspace data and show warnings

- components/common/posts/PostsFeed.tsx
- components/reports/SubjectOverview.tsx
- components/repositories/RepositoriesTable.tsx
Link the timestamp in post card view to post thread view tab in record page instead of record detail page since that's the most common view mods use when reviewing post.
> ❇️ Link to post thread

- components/shell/AuthContext.tsx
When running the ozone UI locally with `yarn dev` but pointing it at an API service on the public internet, it was not possible to login due to an oauth misconfiguration.  This situation is now handled by using a local oauth client.
> Allow local client to be used with public url

- components/mod-event/EventList.tsx
- components/mod-event/useModEventList.tsx
- components/subject/Summary.tsx
This PR applies relevant event stream filters when the following subject summary buttons are clicked
1. record takedown count
2. record escalated count
3. account appeal count
> ❇️ Quick takedown escalation appeal filter

- components/mod-event/useModEventList.tsx
Trusted verifier events are just tag events behind the scenes so event type filter needs to override the types property when trusted verifier event types are selected.
> :bug: Override tag type filter for verification event types

- app/actions/ModActionPanel/BlobList.tsx
- app/actions/ModActionPanel/QuickAction.tsx
- components/common/RecordCard.tsx
- components/common/posts/PostsFeed.tsx
- components/common/posts/PostsTable.tsx
- components/common/posts/ReplyParent.tsx
- components/labeler/DefinitionEditor.tsx
> Reply context link
Along with reply context, this PR also improves vertical spacing in the quick action panel and adds account level tag/label display when reviewing a record to provide additional context about the account without having to switch to account view.
> Account level labels and tags display
> :lipstick: Add reply context when reviewing a post which is a reply to a post

- components/sets/SetList.tsx
- components/sets/useSetList.tsx
Removing a set is already supported by the api but this action was missing in the UI.
> :sparkles: Add remove set action

- components/reports/helpers/subject.ts
When actioning records from workspace, we need the `cid` for each record to build the subject for the event being emitted. however, in most cases, we have this in the workspace data cache already so fetching it from there reduces a bunch of additional queries to the server, reducing chances of hitting any rate limit.
> :zap: Reduce query for workspace action by fetching from react-query cache

- lib/identity.ts
There's no protocol prefix, so the previous technique never worked to resolve a `did:web`. This does.
> :bug: fix did:web did resolution

- components/workspace/Panel.tsx
We initially designed to leave `failed` items selected because of rate limiting being rampant when actioning. over time, we have improved batching a lot and most times, we are performing multiple actions from workspace and leaving actioned items selected is more productive for moderators.
> :sparkles: Leave actioned items selected in workspace after submission

- app/configure/page-content.tsx
- app/events/page-content.tsx
- app/reports/page-content.tsx
- app/repositories/[id]/[...record]/page-content.tsx
- app/repositories/[id]/page-content.tsx
- app/repositories/page-content.tsx
- app/verification/page-content.tsx
- components/email/Composer.tsx
- components/mod-event/EventItem.tsx
- components/mod-event/EventList.tsx
- components/mod-event/ModToolContext.tsx
- components/mod-event/ModToolInfo.tsx
- components/mod-event/helpers/emitEvent.tsx
- components/repositories/MuteReporting.tsx
- components/workspace/Panel.tsx
- components/workspace/PanelActionForm.tsx
- lib/batchId.ts
Ozone backend already allows storing mod tool metadata. This PR displays that info in the UI In a readable way and attaches relevant metadata when events are emitted using ozone client app.
> Workspace event expanded with batch metadata
> Workspace event with metadata collapsed
> Workspace action field for metadata input
> Quick action event
> ❇️ Mod tool metadata support

- app/events/batch/[batchId]/page.tsx
- components/mod-event/EventList.tsx
- components/mod-event/FilterPanel.tsx
- components/mod-event/ModToolInfo.tsx
- components/mod-event/useModEventList.tsx
- components/workspace/PanelActionForm.tsx
- components/workspace/hooks.tsx
- package.json
- service/package.json
- service/yarn.lock
- yarn.lock
Depends on https://github.com/bluesky-social/atproto/pull/4109
- Allows filtering event stream for specific `batchId`
- Adds dedicated page on `/events/batch/[batchId]` route to show all events for a batchId
https://github.com/user-attachments/assets/110579f9-520b-42eb-a79b-b75d0e582cb0
> :sparkles: Add batchId filter for events panel and dedicated batch action viewer

- components/mod-event/FilterPanel.tsx
- components/reports/ReasonBadge.tsx
- components/reports/ReportPanel.tsx
- components/reports/helpers/getType.ts
Depends on https://github.com/bluesky-social/atproto/pull/3881
> New reporting types in event filter panel
> New reporting types in event and tag view
> New reporting types in report panel
> :sparkles: Support expanded custom reporting categories

- components/common/labels/LabelChip.tsx
- components/common/labels/List.tsx
- components/common/labels/Selector.tsx
- components/common/labels/SharedLabelChip.tsx
- components/common/labels/util.ts
- components/config/LabelGroups.tsx
- components/config/Labeler.tsx
- components/config/useLabelGroups.tsx
- cypress/components/configure/LabelGroups.cy.tsx
- cypress/components/labeler/RecordView.cy.tsx
- cypress/e2e/mod-action/label.cy.ts
- cypress/e2e/mod-action/multi-cid-label.cy.ts
- lib/util.ts
This PR uses the options api in ozone to allow creating instance-wide custom groups of labels with color coding and descriptive note to aid moderators visually identify labels quickly in the UI.
https://github.com/user-attachments/assets/3445133f-9f8f-45d3-82f6-81d712045a21
> ❇️ Label Group Configuration
